"""add model_name to token_transaction

Revision ID: 1fed5e89f316
Revises: 20260430_01
Create Date: 2026-05-03 15:59:20.662798
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '1fed5e89f316'
down_revision: Union[str, Sequence[str], None] = '20260430_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_transactions', sa.Column('model_name', sa.String(length=50), server_default='legacy', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_transactions', 'model_name')
    # ### end Alembic commands ###
